global using Library.Application.Common.Exceptions;
global using Library.Infrastructure.DependencyInjection;
global using Library.Infrastructure.Persistence;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.OpenApi;
global using Swashbuckle.AspNetCore.SwaggerUI;
global using System.Net;
global using System.Reflection;
global using System.Text.Json;